### ISSUE TITLE
Get info for bands with same name

### ISSUE THREAD

**Issue by vmorenomarin** [lcharlick/python-metallum#2]
Hi. Thanks by this work!
How I get info from a particular band that has homonym band in MA? _E. g._:

![screenshot_20181009_105634](https://user-images.githubusercontent.com/13444664/46681991-10b95a00-cbb2-11e8-9b3a-b12b571c44b5.png)

**Comment by lcharlick** [comment]
Hey mate, sorry I didn't see your issue - for some reason I didn't get a notification.

I guess it depends on your use case - if you know ahead of time you can supply additional params to the search, e.g.:

```
In [8]: results = metallum.band_search('goliard', countries=['UA']) 
Out[8]: [<SearchResult: Goliard | Black Metal | Lviv >]

In [9]: results[0].get().country
Out[9]: 'Ukraine'
```

These params correspond to the advanced search fields on the archives.

You could also search by album AND artist name:

```
In [17]: results = metallum.album_search('Artissimae Tenebrae', band='Goliard')                                                                                        
Out[17]: [<SearchResult: Goliard | Artissimae Tenebrae | Full-length>]

In [23]: bands = results[0].get().bands                                                                                                                               
Out[23]: [<Band: Goliard>]

In [24]: bands[0].country                                                                                                                         
Out[24]: 'Ukraine'
```

Hope this helps
