### ISSUE TITLE
Getting more than 200 results

### ISSUE THREAD

**Issue by 8135tao** [lcharlick/python-metallum#3]
Hi, awesome work here! When I do search bands by country, 

e.g. `bands = metallum.band_search('*',strict=False, countries=['US'])`

only 200 results (results in the first page when the search is performed on MA) are returned.
is there a way to collect all the bands that are returned from this search? Thanks!

**Comment by lcharlick** [comment]
Hi,

First of all, sorry for the late reply - I didn't have notifications turned on here for some reason 😔

I've added a couple of features that should help you out here - `page_start` and `result_count`:

```
# Fetch total result count for the search
metallum.band_search('*',strict=False, countries=['US']).result_count
> 26340

# Fetch page 2
metallum.band_search('*',strict=False, countries=['US'], page_start=200)
> [<SearchResult: B.R.A.S.H. | Death/Thrash Metal | Tulsa, Oklahoma >,
...]
```

I tried to add a page_size option too but the archives seems to ignore it, even though it's supplied by advanced search 🤔:

<pre>https://www.metal-archives.com/search/ajax-advanced/searching/bands/?bandName=%2A&genre=&country=US&yearCreationFrom=&yearCreationTo=&bandNotes=&status=&themes=&location=&bandLabelName=&sEcho=2&iColumns=3&sColumns=&iDisplayStart=200&<b>iDisplayLength=10</b>&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&_=1541042760591</pre>

**Comment by 8135tao** [comment]
Thanks! That's exactly what I' m looking for!
