### ISSUE TITLE
Genres don't get split correctly in some cases

### ISSUE THREAD

**Issue by jogoe222** [lcharlick/python-metallum#6]
https://github.com/lcharlick/python-metallum/blob/7c6ac8d512bed028bcf052308bbaf54f2eafbba3/metallum.py#L309

In some cases genres not only contain information in parentheses but the information contains commas:

    Heavy Metal/Hard Rock (early, later), Thrash Metal (mid)

If these get split at commas like in the referenced line and again in line 450, the result will be this:

    >>> 'Heavy Metal/Hard Rock (early, later), Thrash Metal (mid)'.split(',')
    ['Heavy Metal/Hard Rock (early', ' later)', ' Thrash Metal (mid)']

Instead it should be:

    ['Heavy Metal/Hard Rock (early, later)', 'Thrash Metal (mid)']

A possible fix would be to use regular expressions to only split at commas not contained in parentheses:

    >>> re.split(r',\s*(?![^()]*\))', 'Heavy Metal/Hard Rock (early, later), Thrash Metal (mid)')
    ['Heavy Metal/Hard Rock (early, later)', 'Thrash Metal (mid)']

**Comment by lcharlick** [comment]
Good catch, and thanks for supplying the correct regex 👍
